apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  labels:
    {{- include "events.labels" . | nindent 4}}
    app.kubernetes.io/component: events
spec:
  replicas: {{ .Values.events.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: events
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: events
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: events
          image: {{ .Values.eventshub.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000