name: Okteto Deployment

on:
  push:
    branches: [main]
    
jobs:
  test:
    uses:  obnubilas/EventHub-Users/.github/workflows/tests.yml@main
    
  deploy:
    needs:  test
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
